### ISSUE TITLE
GenServer.handle_call/3 mock ?

### ISSUE THREAD

**Issue by asmodehn** [msz/hammox#82]
I have been using hammox for a little while, and I recently tried to mock GenServer `handle_call/3` callback.

I ve trimmed my problem down to this script, where I attempt to mock `GenServer.handle_call/3` to provide various implementation to a genserver while testing, as a mock.
`mocktest.exs`:
```elixir
ExUnit.start()

Hammox.defmock(MyMock, for: GenServer)

defmodule GSTest do
  use GenServer

  def start_link(opts) do
    GenServer.start_link(
      __MODULE__,
      {42},
      opts
    )
  end

  def call(srv, req) do
    GenServer.call(srv, req)
  end

  @impl true
  def init(args) do
    {:ok, {"some", "state", args}}
  end

  @impl true
  def handle_call(request, from, state) do
    # transparent forward
    MyMock.handle_call(request, from, state)
  end
end

defmodule GSTest.Test do
  use ExUnit.Case

  import Hammox

  setup do
    proc = start_supervised!({GSTest, name: GSTest.Process})
    %{proc: proc}
  end

  test "lets mock the genserver callback", %{proc: proc} do
    MyMock
    |> allow(self(), proc)
    # replying with the current state
    |> expect(:handle_call, fn (request, from, state) -> {:reply, state, state} end)

    # call and get a response
    {:ok, response} = GenServer.call(proc, {:myrequest, "my_param"})

    # the response is from the mock, returning the actual process state
    assert response == {"some", "state"}
  end
end

```

when running this (with mix run and the proper dependencies installed), I get the following error
```
$ mix run mocktest.exs 
warning: variable "from" is unused (if the variable is not meant to be used, prefix it with an underscore)
  mocktest.exs:46: GSTest.Test."test lets mock the genserver callback"/1

warning: variable "request" is unused (if the variable is not meant to be used, prefix it with an underscore)
  mocktest.exs:46: GSTest.Test."test lets mock the genserver callback"/1

[error] GenServer GSTest.Process terminating
** (MatchError) no match of right hand side value: {:type, 518, :bounded_fun, [{:type, 518, :fun, [{:type, 518, :product, [{:ann_type, 518, [{:var, 518, :request}, {:type, 518, :term, []}]}, {:remote_type, 0, [{:atom, 0, GenServer}, {:atom, 0, :from}, []]}, {:ann_type, 518, [{:var, 518, :state}, {:type, 518, :term, []}]}]}, {:type, 520, :union, [{:type, 519, :tuple, [{:atom, 0, :reply}, {:var, 519, :reply}, {:var, 519, :new_state}]}, {:type, 520, :tuple, [{:atom, 0, :reply}, {:var, 520, :reply}, {:var, 520, :new_state}, {:type, 520, :union, [{:type, 520, :timeout, []}, {:atom, 0, :hibernate}, {:type, 0, :tuple, [{:atom, 0, :continue}, {:type, 520, :term, []}]}]}]}, {:type, 0, :tuple, [{:atom, 0, :noreply}, {:var, 521, :new_state}]}, {:type, 522, :tuple, [{:atom, 0, :noreply}, {:var, 522, :new_state}, {:type, 522, :union, [{:type, 522, :timeout, []}, {:atom, 0, :hibernate}, {:type, 0, :tuple, [{:atom, 0, :continue}, {:type, 522, :term, []}]}]}]}, {:type, 523, :tuple, [{:atom, 0, :stop}, {:var, 523, :reason}, {:var, 523, :reply}, {:var, 523, :new_state}]}, {:type, 524, :tuple, [{:atom, 0, :stop}, {:var, 524, :reason}, {:var, 524, :new_state}]}]}]}, [{:type, 518, :constraint, [{:atom, 518, :is_subtype}, [{:var, 518, :reply}, {:type, 525, :term, []}]]}, {:type, 518, :constraint, [{:atom, 518, :is_subtype}, [{:var, 518, :new_state}, {:type, 525, :term, []}]]}, {:type, 518, :constraint, [{:atom, 518, :is_subtype}, [{:var, 518, :reason}, {:type, 525, :term, []}]]}]]}
    (hammox 0.4.0) lib/hammox.ex:466: Hammox.arg_typespec/2
    (hammox 0.4.0) lib/hammox.ex:375: anonymous fn/2 in Hammox.match_args/2
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (hammox 0.4.0) lib/hammox.ex:374: Hammox.match_args/2
    (hammox 0.4.0) lib/hammox.ex:361: Hammox.match_call/3
    (hammox 0.4.0) lib/hammox.ex:346: anonymous fn/4 in Hammox.check_call/3
    (elixir 1.11.2) lib/enum.ex:3764: Enumerable.List.reduce/3
    (elixir 1.11.2) lib/enum.ex:2231: Enum.reduce_while/3
    (hammox 0.4.0) lib/hammox.ex:345: Hammox.check_call/3
    (hammox 0.4.0) lib/hammox.ex:338: Hammox.protected_code/3
    (stdlib 3.13.2) gen_server.erl:706: :gen_server.try_handle_call/4
    (stdlib 3.13.2) gen_server.erl:735: :gen_server.handle_msg/6
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.513.0>): {:myrequest, "my_param"}
State: {"some", "state", {42}}
Client #PID<0.513.0> is alive

    (stdlib 3.13.2) gen.erl:208: :gen.do_call/4
    (elixir 1.11.2) lib/gen_server.ex:1024: GenServer.call/3
    mocktest.exs:49: GSTest.Test."test lets mock the genserver callback"/1
    (ex_unit 1.11.2) lib/ex_unit/runner.ex:391: ExUnit.Runner.exec_test/1
    (stdlib 3.13.2) timer.erl:166: :timer.tc/1
    (ex_unit 1.11.2) lib/ex_unit/runner.ex:342: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4


  1) test lets mock the genserver callback (GSTest.Test)
     mocktest.exs:42
     ** (exit) exited in: GenServer.call(#PID<0.515.0>, {:myrequest, "my_param"}, 5000)
         ** (EXIT) an exception was raised:
             ** (MatchError) no match of right hand side value: {:type, 518, :bounded_fun, [{:type, 518, :fun, [{:type, 518, :product, [{:ann_type, 518, [{:var, 518, :request}, {:type, 518, :term, []}]}, {:remote_type, 0, [{:atom, 0, GenServer}, {:atom, 0, :from}, []]}, {:ann_type, 518, [{:var, 518, :state}, {:type, 518, :term, []}]}]}, {:type, 520, :union, [{:type, 519, :tuple, [{:atom, 0, :reply}, {:var, 519, :reply}, {:var, 519, :new_state}]}, {:type, 520, :tuple, [{:atom, 0, :reply}, {:var, 520, :reply}, {:var, 520, :new_state}, {:type, 520, :union, [{:type, 520, :timeout, []}, {:atom, 0, :hibernate}, {:type, 0, :tuple, [{:atom, 0, :continue}, {:type, 520, :term, []}]}]}]}, {:type, 0, :tuple, [{:atom, 0, :noreply}, {:var, 521, :new_state}]}, {:type, 522, :tuple, [{:atom, 0, :noreply}, {:var, 522, :new_state}, {:type, 522, :union, [{:type, 522, :timeout, []}, {:atom, 0, :hibernate}, {:type, 0, :tuple, [{:atom, 0, :continue}, {:type, 522, :term, []}]}]}]}, {:type, 523, :tuple, [{:atom, 0, :stop}, {:var, 523, :reason}, {:var, 523, :reply}, {:var, 523, :new_state}]}, {:type, 524, :tuple, [{:atom, 0, :stop}, {:var, 524, :reason}, {:var, 524, :new_state}]}]}]}, [{:type, 518, :constraint, [{:atom, 518, :is_subtype}, [{:var, 518, :reply}, {:type, 525, :term, []}]]}, {:type, 518, :constraint, [{:atom, 518, :is_subtype}, [{:var, 518, :new_state}, {:type, 525, :term, []}]]}, {:type, 518, :constraint, [{:atom, 518, :is_subtype}, [{:var, 518, :reason}, {:type, 525, :term, []}]]}]]}
                 (hammox 0.4.0) lib/hammox.ex:466: Hammox.arg_typespec/2
                 (hammox 0.4.0) lib/hammox.ex:375: anonymous fn/2 in Hammox.match_args/2
                 (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
                 (hammox 0.4.0) lib/hammox.ex:374: Hammox.match_args/2
                 (hammox 0.4.0) lib/hammox.ex:361: Hammox.match_call/3
                 (hammox 0.4.0) lib/hammox.ex:346: anonymous fn/4 in Hammox.check_call/3
                 (elixir 1.11.2) lib/enum.ex:3764: Enumerable.List.reduce/3
                 (elixir 1.11.2) lib/enum.ex:2231: Enum.reduce_while/3
                 (hammox 0.4.0) lib/hammox.ex:345: Hammox.check_call/3
                 (hammox 0.4.0) lib/hammox.ex:338: Hammox.protected_code/3
                 (stdlib 3.13.2) gen_server.erl:706: :gen_server.try_handle_call/4
                 (stdlib 3.13.2) gen_server.erl:735: :gen_server.handle_msg/6
                 (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
     code: {:ok, response} = GenServer.call(proc, {:myrequest, "my_param"})
     stacktrace:
       (elixir 1.11.2) lib/gen_server.ex:1027: GenServer.call/3
       mocktest.exs:49: (test)



Finished in 0.09 seconds (0.08s on load, 0.01s on tests)
1 test, 1 failure

Randomized with seed 249050
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

```

This is with 
```
$ mix -v
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Mix 1.11.2 (compiled with Erlang/OTP 23)
```

So it seems to me that somehow hammox cannot handle [GenServer.handle_call typespec](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/gen_server.ex#L524) ?

I am aware of a simple workaround, which is to have a separate behaviour describing what the handle_call will do, and mock that instead. Which is what I usually do, to keep my GenServers light.

Unfortunately in my actual usecase (adding a more generic behavior for many servers in various apps), I need to mock the same signature as `GenServer.handle_call/3`, so that workaround wouldn't apply.

So, is there a way to mock `GenServer.handle_call/3` ? Am I missing something ?
And Thanks for Hammox!

**Comment by msz** [comment]
That definitely looks like a Hammox bug. Will look into it. Thanks!

**Comment by msz** [comment]
I've done some investigating and it looks like the GenServer typespecs use [type guards](https://hexdocs.pm/elixir/1.12/typespecs.html#defining-a-specification) in function specs which are not yet supported. I've opened #83 to clearly show the problem, so I'll close this issue. Please follow #83 for updates!

In the meantime, a good workaround could be to define your own small GenServer behaviour which only consists of the functionality you actually rely on. This is a good practice regardless of the bug, to clearly show the contracts your application depends on.
